# Generated by Django 2.2.5 on 2019-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=200)),
                ('kingdom_cn', models.CharField(max_length=200)),
                ('phylum', models.CharField(max_length=200)),
                ('phylum_cn', models.CharField(max_length=200)),
                ('subphylum', models.CharField(max_length=200)),
                ('subphylum_cn', models.CharField(max_length=200)),
                ('clazz', models.CharField(max_length=200)),
                ('clazz_cn', models.CharField(max_length=200)),
                ('subclass', models.CharField(max_length=200)),
                ('subclass_cn', models.CharField(max_length=200)),
                ('order', models.CharField(max_length=200)),
                ('order_cn', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('family_cn', models.CharField(max_length=200)),
                ('subfamily', models.CharField(max_length=200)),
                ('subfamily_cn', models.CharField(max_length=200)),
                ('genus', models.CharField(max_length=200)),
                ('genus_cn', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('species_cn', models.CharField(max_length=200)),
                ('name_cn', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_jp', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('habitats', models.CharField(max_length=200)),
                ('part', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
