# Generated by Django 3.0 on 2020-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_auto_20190908_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='tax_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='clazz',
            field=models.CharField(max_length=200, null=True, verbose_name='纲'),
        ),
        migrations.AlterField(
            model_name='species',
            name='clazz_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='纲-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='domain',
            field=models.CharField(max_length=200, null=True, verbose_name='域'),
        ),
        migrations.AlterField(
            model_name='species',
            name='domain_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='域-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(max_length=200, null=True, verbose_name='科'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='科-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(max_length=200, null=True, verbose_name='属'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='属-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom',
            field=models.CharField(max_length=200, null=True, verbose_name='界'),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='界-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_cn',
            field=models.CharField(max_length=200, verbose_name='名称-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='名称-英文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_jp',
            field=models.CharField(max_length=200, null=True, verbose_name='名称-日文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='order',
            field=models.CharField(max_length=200, null=True, verbose_name='目'),
        ),
        migrations.AlterField(
            model_name='species',
            name='order_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='目-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum',
            field=models.CharField(max_length=200, null=True, verbose_name='门'),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='门-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(max_length=200, null=True, verbose_name='种'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='种-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subclass',
            field=models.CharField(max_length=200, null=True, verbose_name='亚纲'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subclass_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='亚纲-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subfamily',
            field=models.CharField(max_length=200, null=True, verbose_name='亚科'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subfamily_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='亚科-中文'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subphylum',
            field=models.CharField(max_length=200, null=True, verbose_name='亚门'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subphylum_cn',
            field=models.CharField(max_length=200, null=True, verbose_name='亚门-中文'),
        ),
    ]
