# Generated by Django 3.0 on 2020-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_auto_20200103_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='habitats',
            field=models.CharField(max_length=200, null=True, verbose_name='生境'),
        ),
        migrations.AlterField(
            model_name='species',
            name='origin',
            field=models.CharField(max_length=200, null=True, verbose_name='源产地'),
        ),
        migrations.AlterField(
            model_name='species',
            name='part',
            field=models.CharField(max_length=200, null=True, verbose_name='食用部位'),
        ),
        migrations.AlterField(
            model_name='species',
            name='type',
            field=models.CharField(max_length=200, null=True, verbose_name='食物种类'),
        ),
    ]
