# Generated by Django 2.2.5 on 2019-09-08 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='domain_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='clazz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='clazz_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='family_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='habitats',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_jp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='order',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='order_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='part',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subclass',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subclass_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subfamily',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subfamily_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subphylum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='subphylum_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
